vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|16 Mar 2009 16:27:01 -0000
vti_author:SR|DCA-HSWEB-01\\webadmin_agfirst
vti_modifiedby:SR|DCA-HSWEB-01\\webadmin_agfirst
vti_nexttolasttimemodified:TR|16 Mar 2009 16:27:01 -0000
vti_timecreated:TR|15 Jun 2011 13:00:32 -0000
vti_extenderversion:SR|5.0.2.6819
vti_syncwith_www.agfirst.com\:80:TR|16 Mar 2009 16:27:01 -0000
vti_lineageid:SR|{BE2F0D11-8FC1-46B6-9058-594EAE297537}
vti_cacheddtm:TX|15 Jun 2011 13:00:32 -0000
vti_filesize:IR|1248
vti_backlinkinfo:VX|
