vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|16 Mar 2009 16:29:57 -0000
vti_author:SR|DCA-HSWEB-01\\webadmin_agfirst
vti_modifiedby:SR|DCA-HSWEB-01\\webadmin_agfirst
vti_nexttolasttimemodified:TR|16 Mar 2009 16:29:57 -0000
vti_timecreated:TR|15 Jun 2011 13:00:21 -0000
vti_extenderversion:SR|5.0.2.6819
vti_syncwith_www.agfirst.com\:80:TR|16 Mar 2009 16:29:57 -0000
vti_lineageid:SR|{E29A51FB-B6AC-477F-8B8B-DF16F1D3E365}
vti_cacheddtm:TX|15 Jun 2011 13:00:21 -0000
vti_filesize:IR|1388
vti_backlinkinfo:VX|
