		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="images/Directors/wheeler.jpg" width="201" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>J. Mark Wheeler, from Brandenton, Florida is chief financial officer of Wheeler Farms, inc., which grows citrus in Brevard, Desoto, Glades and Polk Counties in Florida.  He serves on the boards of Farm Credit of Southwest Florida, ACA, Florida Citrus Mutual, an industry trade association, and Wheeler Brothers, Inc., a family-held citrus contract harvesting corporation.  Mr. Wheeler is president of Hardee Livestock Market, Inc., a beef cattle operation, and Boston Mining Company, a citrus, real estate and cash investment organization.  Mr. Wheeler serves on the Board Audit Committee. Mr. Wheeler became a director in January 2009 and his term expires December 31, 2012.<br/>
	          </td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">J. Mark Wheeler </span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>