		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="http://www.agfirst.com/images/Directors/KELLY2.jpg" width="200" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>Thomas W. Kelly, Chairman of the Board, is a farmer from Tyrone, Pennsylvania. A former dairyman and breeder of Registered Holsteins, his farming operation now includes raising dairy heifers and growing corn, soybeans and hay.  Along with his son, he handles land management for Spring Lane Hunt Club.  He currently is an elected delegate to the Penn State Agricultural Council and a director of Mid-Atlantic Master Farmer Association and is a former director of Holstein Association, USA.  Mr. Kelly currently serves as Chairman of the Board Governance Committee.   Mr. Kelly became a director in 2001and his term expires December 31, 2012.</p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">Thomas W. Kelly, Chairman</span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>