		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="http://www.agfirst.com/images/Directors/may_jim.jpg" width="200" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>James L. May is owner and operator of Mayhaven Farm in Waynesburg, Kentucky, where he owns 330 acres and leases another 700 acres.  He is involved in the development and marketing of 500 heifers for replacement cows and embryo transfer.  Mr. May’s operation also includes 150 acres of alfalfa hay, 500 acres of corn and soybeans, and 100 acres of wheat. He currently serves as a member of the Central Kentucky Ag Credit board, Lincoln County Extension Council, Lincoln County Ag Development Board, and is a member of the Lincoln County Farm Bureau Board.  Mr. May served on the Board Audit Committee, and currently serves as chairman of the Board Credit Committee.  Mr. May became a director in 2006 and his term expires December 31, 2009.</p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">James L. May</span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>