		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="http://www.agfirst.com/images/Directors/Holden1.jpg" width="200" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>Robert L. Holden, Sr. is co owner and operator of a dairy, a 900 acre row crop farm, and a 200,000 broiler operation in Whigham, Georgia.  He is a director of the Southwest Georgia Farm Credit, ACA, Georgia Milk Producers, Grady County Farm Bureau, American Dairy Association of Georgia, and First United Ethanol, LLC.  Mr. Holden serves on the Board Governance Committee.  Mr. Holden became a director in 1995 and his term expires December 31, 2010.</p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">Robert L. Holden, Sr.</span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>