<table width="460" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td valign="top"><p class="style11"><span class="style12">B</span>OARD <span class="style11">OF <span class="style12">D</span>IRECTORS</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<i><font size="2">as of January 1, 2011</font></i></p>
                    <table bordercolor="#CCCCCC" cellspacing="2" cellpadding="2" width="450" border="0">
                      <tbody>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" align="center" valign="top" background="images2/bg-title-director.jpg" class="style11">Name </td>
                          <td width="131" align="center" valign="top" background="images2/bg-title-director.jpg" class="style11">Term Ends </td>
                          <td width="138" align="center" valign="top" background="images2/bg-title-director.jpg" class="style11">Committee <span class="style17">Assignment</span> </td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-GaryLAlexander.asp" >Gary L. Alexander</a> </p></td>
                          <td valign="top" class="style5"><p> December 31, 2011 </p></td>
                          <td valign="top" class="style5"><p>Audit &amp; Examination </p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-WilliamCBessJr.asp">William C. Bess, Jr. </a></p></td>
                          <td width="131" valign="top" class="style5"><p>December 31,   2009</p></td>
                          <td width="138" valign="top" class="style5"><p>Governance </p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-DonWFreeman.asp" >Don W. Freeman</a></p></td>
                          <td width="131" valign="top" class="style5"><p>December 31,   2009</p></td>
                          <td width="138" valign="top" class="style5">Compensation </td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-DaleRHershey.asp" >Dale R. Hershey </a></p></td>
                          <td valign="top" class="style5"><p>December 31, 2011 </p></td>
                          <td valign="top" class="style5"><p>Credit</p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-RobertLHoldenSr.asp" >Robert L. Holden, Sr.</a></p></td>
                          <td width="131" valign="top" class="style5"><p>December 31, 2010 </p></td>
                          <td width="138" valign="top" class="style5"><p>Governance   &nbsp;</p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-PaulMHouse.asp" >Paul M. House </a></p></td>
                          <td width="131" valign="top" class="style5"><p>
							December 31, 2011 </p></td>
                          <td width="138" valign="top" class="style5"><p>Board Chairman</p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-ThomasWKelly.asp" >Thomas W. Kelly </a></p></td>
                          <td width="131" valign="top" class="style5"><p>December 31, 2012</p></td>
                          <td width="138" valign="top" class="style5"><p>Governance </p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-LyleRayKing.asp" >Lyle Ray King </a></p></td>
                          <td width="131" valign="top" class="style5"><p>December 31, 2012</p></td>
                          <td width="138" valign="top" class="style5"><p>Credit</p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-MWayneLambertson.asp" >M. Wayne Lambertson </a></p></td>
                          <td width="131" valign="top" class="style5"><p>December 31,   2009</p></td>
                          <td width="138" valign="top" class="style5"><p>Board 
							Vice Chairman </p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5">&nbsp;&nbsp;<a href="board-of-directors-JamesLMay.asp" >James L. May</a></td>
                          <td width="131" valign="top" class="style5">December 31,   2009</td>
                          <td width="138" valign="top" class="style5">Credit</td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-EugeneWMerrittJr.asp" >Eugene W. Merritt, Jr. </a></p></td>
                          <td width="131" valign="top" class="style5"><p>December 31, 2010 </p></td>
                          <td width="138" valign="top" class="style5"><p>Compensation </p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td valign="top" class="style5">&nbsp;&nbsp;<a href="board-of-directors-JamesMNorsworthyIII.asp" >James M. Norsworthy </a></td>
                          <td valign="top" class="style5">December 31, 2011</td>
                          <td valign="top" class="style5">Audit &amp; Examination</td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5">&nbsp;&nbsp;<a href="board-of-directors-KatherineAPace.asp" >Katherine A. Pace</a> </td>
                          <td width="131" valign="top" class="style5">December 
							31, 2011</td>
                          <td width="138" valign="top" class="style5">Audit &amp; Examination</td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-JDanRainesJr.asp" >J. Dan Raines, Jr. </a></p></td>
                          <td width="131" valign="top" class="style5"><p>December 31, 2009 </p></td>
                          <td width="138" valign="top" class="style5"><p>Credit</p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-WalterLSchmidlenJr.asp" >Walter Schmidlen </a></p></td>
                          <td width="131" valign="top" class="style5"><p>December 31, 2012</p></td>
                          <td width="138" valign="top" class="style5"><p>Governance </p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-RobertGSexton.asp" >Robert G. Sexton </a></p></td>
                          <td width="131" valign="top" class="style5"><p>
							December 31, 2011</p></td>
                          <td width="138" valign="top" class="style5"><p>Audit &amp; Examination </p></td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5">&nbsp;&nbsp;<a href="board-of-directors-RobertHSpiersJr.asp" >Robert H. Spiers, Jr. </a></td>
                          <td width="131" valign="top" class="style5">December 31, 2009</td>
                          <td width="138" valign="top" class="style5">Compensation </td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td width="149" valign="top" class="style5">&nbsp;&nbsp;<a href="board-of-directors-WilliamHVoss.asp" >William H. Voss</a></td>
                          <td width="131" valign="top" class="style5">December 31, 2014</td>
                          <td width="138" valign="top" class="style5">Compensation </td>
                        </tr>
                        <tr onMouseOver="this.className = 'hlt';" onMouseOut="this.className = '';" height="18">
                          <td valign="top" class="style5"><p>&nbsp;&nbsp;<a href="board-of-directors-JMWheeler.asp" >J. Mark Wheeler</a></p></td>
                          <td valign="top" class="style5"><p>December 31, 2012</p></td>
                          <td valign="top" class="style5"><p>Audit &amp; Examination</p></td>
                        </tr>
                      </tbody>
                    </table></td>
              </tr>
            </table>
              <br>
              <table width="333" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                  <td align="center">
					<a target="_blank" class="style5" href="http://www.agfirst.com/Committee%20Charter%20Approved-2006.doc">Review our Audit Committee Charter here</a></td>
                </tr>
              </table>