		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="http://www.agfirst.com/images/Directors/PaulHouse.jpg" width="200" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>Paul M. House, Vice Chairman of the Board, is from Nokesville, Virginia, where he grows corn, soybeans, wheat, hay and turf grass.  He also operates a dairy.  He serves as a director of the Farm Credit of the Virginias, ACA.  Mr. House served on the Board Compensation Committee.  He currently serves as Chairman of the Board.  Mr. House became a director in 2002 and his term expires December 31, 2011.</p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">Paul M. House</span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>