		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="http://www.agfirst.com/images/Directors/JamesNorsworthy.jpg" width="200" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>James M. Norsworthy, III, from Jackson, Louisiana runs 100 Cedars Cattle Farm, a 175-head cow-calf operation.  He also has a commercial hay operation with 125 acres in Alicia Bermuda hay and 150 acres in Bahia Grass hay and manages a 375-acre pine and hardwood timber operation. He is a member of the board of directors of First South Farm Credit, ACA, serves on the board of Feliciana Farm Bureau and is a past president of that organization.  He is a member of East Feliciana Cattlemen’s Association, American Angus Association and the Feliciana Forestry Association. Mr. Norsworthy served as a former mayor of the town of Jackson, La.  Mr. Norsworthy serves on the Board Audit Committee.  Mr. Norsworthy became a director in 2008 and his term expires December 31, 2011.</p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">James M. Norsworthy, III </span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>