		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="http://www.agfirst.com/images/Directors/Bess1.jpg" width="200" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>William C. Bess, Jr., from Lincolnton, North Carolina, is owner of Bess Farms. Inc., a grain and hay production operation and has a 70-head cow-calf operation.  He serves on the boards of the national Farm Credit Council Board, the Farm Credit System’s national trade organization, Farm Credit Council Services, and Carolina Farm Credit, ACA.  He is also a member of the Cleveland County and Catawba Cattlemen’s Associations.  Mr. Bess serves on the Board Governance Committee.  Mr. Bess became a director in 1995 and his term expires December 31, 2009.
		  </p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">William C. Bess, Jr.,</span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>