<html>
<!--#include file="cdovbs.inc" -->
<%
Dim objMail
strWho = Request ("UserName")
strTo = Request("UserEmail")
strFrom = Request.ServerVariables("SERVER_NAME")
Set objMail = CreateObject("CDONTS.NewMail")
objMail.From = strFrom
objMail.To = strTo
objMail.Subject = "Mail Works!!!"
objMail.Body = "Dear " & strWho & ". This e-mail was generated by server using CDO for NTS(CDONTS)."
objMail.importance = cdoHigh
objMail.Send
Set objMail = nothing
%>

<head>
<title>confirm</title>
<link rel="stylesheet" type="text/css" href="index.css">
</head>

<body BGCOLOR="white">
<blockquote>
<div align="right"><h2>mail sent</h2></div><hr>
<ul>
<h2>Mail sent</h2>
	<li>Please check your &quot;Mail Box&quot;.
</ul>
<blockquote>

</font>

<!-- Google Analytics Tracking Code -->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34898365-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<!-- End Google Analytics Tracking Code -->

</body>
</html>
