vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|16 Mar 2009 16:19:54 -0000
vti_author:SR|DCA-HSWEB-01\\webadmin_agfirst
vti_modifiedby:SR|DCA-HSWEB-01\\webadmin_agfirst
vti_nexttolasttimemodified:TR|16 Mar 2009 16:19:54 -0000
vti_timecreated:TR|15 Jun 2011 13:00:32 -0000
vti_extenderversion:SR|5.0.2.6819
vti_syncwith_www.agfirst.com\:80:TR|16 Mar 2009 16:19:54 -0000
vti_lineageid:SR|{95D75D45-E553-4AD3-B68F-2BF5E7AF58DB}
vti_cacheddtm:TX|15 Jun 2011 13:00:32 -0000
vti_filesize:IR|1265
vti_backlinkinfo:VX|
