vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|15 Feb 2011 13:17:31 -0000
vti_title:SR|AgFirst Farm Credit Bank
vti_author:SR|DCA-HSWEB-01\\webadmin_agfirst
vti_modifiedby:SR|DCA-HSWEB-01\\webadmin_agfirst
vti_nexttolasttimemodified:TR|15 Feb 2011 13:17:31 -0000
vti_timecreated:TR|15 Jun 2011 13:01:43 -0000
vti_extenderversion:SR|5.0.2.6819
vti_syncwith_www.agfirst.com\:80:TR|15 Feb 2011 13:17:31 -0000
vti_cacheddtm:TX|15 Jun 2011 13:01:43 -0000
vti_filesize:IR|10667
vti_cachedtitle:SR|AgFirst Farm Credit Bank
vti_cachedbodystyle:SR|<body onLoad="MM_preloadImages('images/btn-news2.jpg','images/btn-account2.jpg','images/btn-capital2.jpg','images/btn-horizon2.jpg','images/btn-news-finance2.jpg','images/btn-correspondent2.jpg','images/text-news.jpg','images/text-account.jpg','images/text-capital.jpg','images/text-horizons.jpg','images/text-financials.jpg','images/text-home-loans.jpg','images2/n-butn-about2.jpg','images2/n-butn-new2.jpg','images2/n-butn-corresponent2.jpg','images2/n-butn-find2.jpg')">
vti_cachedlinkinfo:VX|Q|agfirst-style2.css S|images/bg-center.jpg S|images/1.jpg S|images/new-home-header.jpg K|index.asp H|contact.html H|ssmuaccountaccess.html H|employment.html H|index.asp S|images/spacer.gif S|images/menu1.jpg H|about.html S|images2/n-butn-about.jpg H|news.html S|images2/n-butn-new.jpg H|capital-markets.html S|images/btn-capital.jpg K|index.asp H|correspondent-lending.html S|images2/n-butn-corresponent.jpg H|find-a-lender.html S|images2/n-butn-find.jpg S|images2/n-butn-blank.jpg S|images/menu-btm.jpg S|images/spacer.gif S|hslides2.js S|images/border.jpg S|images/spacer.gif H|find-a-lender.html H|http://www.countrymortgages.com/flash/offices.html S|images2/new-map.jpg S|images/btm-div.jpg H|links-disclaimer.html H|privacy-policy.html H|equal-housing-lender.html H|equal-housing-lender.html H|equal-housing-lender.html H|index.asp K|index.asp S|images/footer.jpg K|index.asp K|index.asp K|index.asp K|index.asp
vti_cachedsvcrellinks:VX|FQUS|agfirst-style2.css NSUS|images/bg-center.jpg NSUS|images/1.jpg NSUS|images/new-home-header.jpg FKUS|index.asp FHUS|contact.html FHUS|ssmuaccountaccess.html FHUS|employment.html FHUS|index.asp NSUS|images/spacer.gif NSUS|images/menu1.jpg FHUS|about.html NSUS|images2/n-butn-about.jpg FHUS|news.html NSUS|images2/n-butn-new.jpg FHUS|capital-markets.html NSUS|images/btn-capital.jpg FKUS|index.asp FHUS|correspondent-lending.html NSUS|images2/n-butn-corresponent.jpg FHUS|find-a-lender.html NSUS|images2/n-butn-find.jpg NSUS|images2/n-butn-blank.jpg NSUS|images/menu-btm.jpg NSUS|images/spacer.gif FSUS|hslides2.js NSUS|images/border.jpg NSUS|images/spacer.gif FHUS|find-a-lender.html NHHS|http://www.countrymortgages.com/flash/offices.html NSUS|images2/new-map.jpg NSUS|images/btm-div.jpg FHUS|links-disclaimer.html FHUS|privacy-policy.html FHUS|equal-housing-lender.html FHUS|equal-housing-lender.html FHUS|equal-housing-lender.html FHUS|index.asp FKUS|index.asp NSUS|images/footer.jpg FKUS|index.asp FKUS|index.asp FKUS|index.asp FKUS|index.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1 AgFirst\\ Farm\\ Credit\\ Bank\\ is\\ part\\ of\\ the\\ Farm\\ Credit\\ System,\\ the\\ largest\\ \r\nagricultural\\ lending\\ organization\\ in\\ the\\ United\\ States.
vti_charset:SR|windows-1252
vti_lineageid:SR|{47E3C402-BBBD-447C-A2F4-D08E03E76AEF}
vti_backlinkinfo:VX|map-pa.html contact.html board-of-directors-JimmyPoston.asp board-of-directors-JamesCarter.asp news.html map-tn.html map-sc.html board-of-directors-WilliamHVoss.asp board-of-directors-KatherineAPace.asp map-va.html links-disclaimer.html index_new.html history.html employment-mjs.html browserredirect.htm index3.html index-withfinanciallink.asp default.asp board-of-directors-KennethASpearman.asp board-of-directors-JamesMNorsworthyIII.asp board-of-directors-GaryLAlexander.asp board-of-directors-JohnSLangford.asp news-with-financials.html map-fl.html links.html find-a-lender.html board-of-directors-RobertHSpiersJr.asp board-of-directors-LyleRayKing.asp board-of-directors-BobbyMcCollum.asp about3.html about.html ssmuaccountaccessterms.html ssmuaccountaccess.html news-bkup.html new.html map-md.html board-of-directors-JDanRainesJr.asp employment-bkup.html correspondent-lending.html farm-credit-system.html farm-credit-system-bkup.html Copy\\ of\\ find-a-lender.html capital-markets.html board-of-directors.asp board-of-directors-WilliamCBessJr.asp board-of-directors-JMWheeler.asp map-nc.html map-de.html find-a-lender2.html employment-mailing-list.html board-of-directors.html board-of-directors-MWayneLambertson.asp board-of-directors-JamesLMay.asp privacy-policy.html board-of-directors-EugeneWMerrittJr.asp board-of-directors-BonnieHancock.asp new2.html map-oh.html code-of-ethics.html board-of-directors-ThomasWKelly.asp board-of-directors-test.asp ssmuaccountaccess-bkup.html map-mi.html map-ga.html index2.html index.asp board-of-directors-AlanMarsh.asp map-w-va.html map-al.html equal-housing-lender.html contact-information.html contact-bkup.html board-of-directors-WalterLSchmidlenJr.asp board-of-directors-RobertLHoldenSr.asp board-of-directors-PaulMHouse.asp about-bkup.html contact-information-thankyou.asp community-article1.html board-of-directors-s1.html board-of-directors-DonWFreeman.asp senior-officers.html farm-credit-banks.html employment.html board-of-directors-RobertGSexton.asp board-of-directors-edit.asp board-of-directors-DaleRHershey.asp previousyearnewsreleases.html mission-vision-values.html map-wv.html district-financial-reports.html map-ky.html employment-mailing-thankyou.asp board-of-directors-new.asp previousyearfinancials.html our-community.html map-pr.html map-la.html board-of-directors-JackBentley.asp
