		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="http://www.agfirst.com/images/Directors/Voss-LO.jpg" width="200" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>William H. Voss, is from McComb, Mississippi. He has commercial cattle and timber operations in Southwest Mississippi and is involved in land and commercial property management. His career includes production agriculture, agribusiness and real estate.  He currently serves on the Board of directors of First South Farm Credit, ACA.  He is a former agricultural commodities and securities broker and has served as Chairman of the Mississippi Real Estate Commission and Chairman of the Pike County Farm Service Committee.  Mr. Voss serves on the Board Compensation Committee, and is a member of the AgFirst/FCBT Plan Sponsor Committee.  Mr. Voss became a director in 2007 and his term expires December 31, 2010.</p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">William H. Voss </span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>