		<tr bgcolor="#FFFFFF">
			<td>
			<!--img border="0" src="http://www.agfirst.com/images/Directors/William-Robinson.jpg" width="200" height="300"--></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>Robinson is a professional engineer in Lexington, S.C., and a third-generation farmer. He has owned and operated Robinson Family Farms, which consists of 40 acres of row crops and 200 acres of timber, for nearly a quarter of a century. He is also involved in a partnership that leases a 100-acre cow and calf farm with 50 head of cattle, as well as 10 acres of coastal Bermuda hay. Robinson retired earlier this year from Santee Cooper, South Carolina’s publicly owned utility. A director with AgSouth Farm Credit since 2011, he currently serves as vice chairman of the Board for that AgFirst Association. He also is a member of the AgFirst Benefits Plan Sponsor Committee and the AgFirst/FCBT Benefits Plan Sponsor Committee. Robinson received both his B.S. and M.S. in civil engineering from Clemson University. He also earned an MBA from Charleston Southern University.</p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">William Robinson</span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>