		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="http://www.agfirst.com/images/Directors/Raines3.jpg" width="200" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>J. Dan Raines, Jr. is a beef producer from Ashburn, Georgia.  His operations include commercial beef cattle, registered Angus cattle and timber.  He serves as a director on the boards of AgGeorgia Farm Credit, ACA and the Federal Agricultural Mortgage Corporation (Farmer Mac).  Mr. Raines served on the Board Compensation Committee, and currently serves on the Board Credit Committee.  Mr. Raines became a director in 1995 and his term expires December 31, 2009.
			</p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">J. Dan Raines, Jr. </span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>