		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="http://www.agfirst.com/images/Directors/SCHMIDLEN6.jpg" width="200" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>Walter L. Schmidlen, Jr., from Elkins, West Virginia, is a past dairy farmer and now continues his cow-calf operation along with growing hay and corn on a 700 acre farm with lease/rented land.  He is owner/operator of a farm equipment business.  He presently serves on the board of the Farm Credit of the Virginias, ACA, and was a former director of Southern States Cooperative and Sire Power.   Mr. Schmidlen serves on the Board Governance Committee.  Mr. Schmidlen became a director in 2001 and his term expires December 31, 2012.</p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">Walter L. Schmidlen, Jr. </span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>