		<tr bgcolor="#FFFFFF">
			<td>
			<img border="0" src="http://www.agfirst.com/images/Directors/ray-iC.jpg" width="200" height="300"></td>
			<td valign="top" bgcolor="#FFFFFF" width="90%">
			<table width="90%" align="center"><tr><td valign="top" class="style5"><p>Lyle Ray King of Ash, North Carolina, owns and operates a farm where he grows timber, corn, soybeans and wheat.  He currently serves on the boards of Cape Fear Farm Credit, ACA, Atlantic Telephone Membership Cooperative, and Landbank Resource Management, a real estate company.  Mr. King served on the Board Governance Committee, and currently serves on the Board Credit Committee.  Mr. King became a director in 2005 and his term expires December 31, 2012.</p></td></tr></table></td>
		</tr>
		<tr>
		  <td colspan="2" bgcolor="#FFFFFF"><span style="font-weight: 700" ><font face="Verdana,Arial,Helvetica" size="4"><span class="style11">Lyle Ray King</span></font></span><font face="Verdana,Arial,Helvetica" size="4"><span style="font-weight: 700"></span></font></td>
	  </tr>